import type { TrackingEvent } from './types';
import { createHash } from 'crypto';

export class EmailTracker {
  private trackingBaseUrl: string;

  constructor(baseUrl: string = process.env.TRACKING_BASE_URL || 'http://localhost:3001') {
    this.trackingBaseUrl = baseUrl;
  }

  generateTrackingId(campaignContactId: string): string {
    const hash = createHash('sha256')
      .update(`${campaignContactId}-${Date.now()}-${Math.random()}`)
      .digest('hex')
      .slice(0, 32);
    return hash;
  }

  generateTrackingPixel(trackingId: string): string {
    return `<img src="${this.trackingBaseUrl}/t/open/${trackingId}" width="1" height="1" alt="" style="display:none" />`;
  }

  wrapLinks(html: string, trackingId: string): string {
    const linkRegex = /<a\s+(?:[^>]*?\s+)?href=(["'])(.*?)\1([^>]*)>/gi;
    return html.replace(linkRegex, (match, quote, url, rest) => {
      const trackedUrl = `${this.trackingBaseUrl}/t/click/${trackingId}?url=${encodeURIComponent(url)}`;
      return `<a href="${trackedUrl}"${rest}>`;
    });
  }

  injectTracking(html: string, trackingId: string): string {
    const withTrackedLinks = this.wrapLinks(html, trackingId);
    if (html.includes('</body>')) {
      return withTrackedLinks.replace('</body>', `${this.generateTrackingPixel(trackingId)}</body>`);
    }
    return withTrackedLinks + this.generateTrackingPixel(trackingId);
  }

  isAutoReply(headers: Record<string, string>): boolean {
    const autoReplyHeaders = [
      'auto-submitted',
      'x-autoreply',
      'x-autorespond',
      'precedence',
      'x-autogenerated',
    ];

    for (const header of autoReplyHeaders) {
      const value = headers[header]?.toLowerCase() || '';
      if (
        value.includes('auto-') ||
        value.includes('auto_') ||
        value === 'bulk' ||
        value === 'auto_reply'
      ) {
        return true;
      }
    }
    return false;
  }
}
